get_translation:
  name: Get Translation
  description: Get a translation for a specific key and language
  fields:
    language:
      name: Language
      description: Language code (e.g., 'ru', 'en', 'de')
      required: true
      selector:
        text:
    key:
      name: Translation Key
      description: Translation key (e.g., 'state.vacuum.cleaning')
      required: true
      selector:
        text:

bulk_get_translations:
  name: Bulk Get Translations
  description: Get multiple translations at once
  fields:
    language:
      name: Language
      description: Language code (e.g., 'ru', 'en', 'de')
      required: true
      selector:
        text:
    keys:
      name: Translation Keys
      description: List of translation keys
      required: true
      selector:
        object:

clear_translations:
  name: Clear All Translations
  description: Clear all stored translations from the sensor
